FROM docker.io/library/ubuntu:24.04 as unison
ARG TARGETARCH TARGETOS TARGETPLATFORM TARGETVARIANT

# Install dependencies
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=${TARGETPLATFORM}/var/cache/apt \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update -qq && \
    apt-get install -qy --no-install-recommends \
      sudo \
      tini \
      unison \
      openssh-server \
      && \
    apt-get autoremove -y && rm -rf /var/lib/apt/lists/* && \
    echo "ubuntu ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

ENV TZ=UTC

EXPOSE 22

USER ubuntu
WORKDIR /home/ubuntu

COPY --chmod=755 ubuntu-24.04/unison.sh /usr/local/bin/unison.sh

CMD [ "/usr/local/bin/unison.sh"]
