#!/bin/sh -ex


UNISON_LOCAL_DIRECTORY=${UNISON_LOCAL_DIRECTORY:-/home/ubuntu/data}
UNISON_REPEAT=${UNISON_REPEAT:-watch+3600}
UNISON_PREFER=${UNISON_PREFER:-newer}

CONTAINERS_CLI_TOOL=${CONTAINERS_CLI_TOOL:-podman}
UNISON_IMAGE_REGISTRY=${UNISON_IMAGE_REGISTRY:-ghcr.io/doganulus}
UNISON_IMAGE_NAME=${UNISON_IMAGE_NAME:-unison}
UNISON_IMAGE_VERSION=${UNISON_IMAGE_VERSION:-ubuntu-24.04}
UNISON_SERVERCMD="${CONTAINERS_CLI_TOOL} run --rm ${UNISON_IMAGE_REGISTRY}/${UNISON_IMAGE_NAME}:${UNISON_IMAGE_VERSION} unison -server"

unison "${UNISON_LOCAL_DIRECTORY}" ssh://"${UNISON_REMOTE_HOST}"/"${UNISON_REMOTE_DIRECTORY}" \
    -auto \
    -batch \
    -repeat "${UNISON_REPEAT}" \
    -prefer "${UNISON_PREFER}" \
    -servercmd "${CONTAINERS_CLI_TOOL}" run --rm \
        ${UNISON_IMAGE_REGISTRY}/${UNISON_IMAGE_NAME}:${UNISON_IMAGE_VERSION} unison -server
    